### ISSUE TITLE
Compress Images with pngquant

### ISSUE THREAD

**Issue by taubmann** [Zettlr/zettlr-docs#110]
Some Images on the Website (like the first one on the Homepage) are quite heavy. It would make sense to reduce the image size with an compressor like [pngquant](https://pngquant.org) (the size on the mentioned one could be reduced from 2.5 MB to 71 KB)

**Comment by nathanlesage** [comment]
Yeah there's definitely room for improvement. I'm already thinking about a potential different nice landing page, but I also take any advice on making it better! I won't do much about that heavy image on the startpage though, since that will be exchanged soon either way, and I'll make sure to make the new one much smaller!

In any case, it would be great if anything related to the website could be directed to the main Zettlr repository :)
