### ISSUE TITLE
"Guide: Zettlr as Zettelkasten" / "Step 1"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Zettlr/zettlr-docs#115]
This section in the docs about "Zettelkasten" is inconsistent and incomplete.

https://docs.zettlr.com/en/guides/guide-zettelkasten/#step-1-adjust-the-settings

Most of the mentioned settings do not exist in the current `1.8.9` release (Debian 11 via AppImage).

**Comment by nathanlesage** [comment]
Unfortunately, because we are in the transition phase from 1.8.9 to 2.0.0, the docs are in kind of a bad state, I admit. These guides will be removed beginning with 2.0.0.

Additionally, we rely on the community helping with fixing docs because otherwise it's just too much work, so feel free to open PRs fixing things!

Lastly, I do recommend that you switch to the 2.0.0 beta. It's not yet formally stable, but practically it is and it is much superior to 1.8.9 which does expose quite a few bugs.
