### ISSUE TITLE
Zettlr hangs on opening [Windows]

### ISSUE THREAD

**Issue by loopernow** [Zettlr/zettlr-docs#188]
First I tried to open my Desktop folder as my workspace…Zettlr did not like that and said it was unable to. So I tried adding my user folder instead. Now Zettlr hangs on startup, saying it's about halfway done with loading that folder (but it hangs).

**Comment by wideaperture** [comment]
Hi @loopernow,

This repo/issues list is for the Zettlr documentation. To report an issue with the app itself, you can go to [the issues list for the app repo.](https://github.com/Zettlr/Zettlr/issues?q=is%3Aissue+is%3Aopen).

That said, I have an idea of how to fix this. Zettlr is presumably hanging because the total number of files in your home folder and its subdirectories is collectively too large for it to handle. So, at least to start, I'd suggest removing the home folder from the list of workspaces Zettlr attempts to open on startup. To do this, you can remove the mention of the home folder in Zettlr's `config.json` file, which on Windows can be found in `C:\Users\<your username>\AppData\Roaming\Zettlr`. (Note that `AppData` is a hidden folder, so you may need to adjust your File Explorer preferences to locate it.)

If you open `config.json` in your Notepad app, you'll see a line near the beginning of the file that points to your home folder. Remove that line, save the file, and try re-opening Zettlr.

If you have additional help requests, note that the [Zettlr Discord channel](https://discord.gg/PcfS3DM9Xj) is a good place to ask. Or, if it's a bug, you can file a ticket under the main app repo.

**Comment by loopernow** [comment]
Thank you so much @wideaperture. I was able to get Zettlr to open using your instructions; and sorry about posting my issue in the wrong place!
