### ISSUE TITLE
[Feature] Open linked file with corresponding app instead of browser

### ISSUE THREAD

**Issue by raphraph** [Zettlr/zettlr-docs#86]
I really like the ability to add non markdown files to folder and see them in the sidebar (as attachments).

However, if I add a link to say a pdf file or a LibreOffice file for example, when CTRL+clicking the link it tries to open the file in my web browser.
If I click on the file directly in the sidebar it opens the file with the correct corresponding app (PDF viewer or LibreOffice in my examples).

It would be nice that Zettlr could distinguish, in links, URLs which need to be opened with a web browser from other file types which must be opened with other apps.

**Comment by nathanlesage** [comment]
This is easy: Make sure to prepend some indication to the path that indicates that it's indeed a file on your computer (e.g. `./file.pdf` instead of `file.pdf`). There will be further improvements later!

However, this is the wrong repository, please issue such requests on our main repository: https://github.com/Zettlr/Zettlr/issues

**Comment by raphraph** [comment]
Oops, sorry for my inattention... I didn't see that I had navigated to the docs repository.

However your tip does not seem to work for me... this is already what I was doing, like this :
`[name_of_file.pdf](/full/path/to/my/name_of_file.pdf)`

I can make an issue in the correct repo if you confirm that it is one.

**Comment by nathanlesage** [comment]
Oh? Doesn't work, even with absolute path? Weird, I'll see to it! :) If it isn't fixed by the end of the year, feel free to open an issue on the main repo!

**Comment by raphraph** [comment]
I can confirm it is fixed in 1.8.1. Thanks.

**Comment by MatveyM11** [comment]
> This is easy: Make sure to prepend some indication to the path that indicates that it's indeed a file on your computer (e.g. `./file.pdf` instead of `file.pdf`). There will be further improvements later!

That's was pretty useful, I've encountered same problem when I tried to make a relative path to a .pptx. With markdown files Zettlr was fine but with a path to .pptx it kept opening the browser, though Okular was able properly open a LibreOffice.
With edding `./` In the beginning everything started to work fine.

I think such miscelannious stuff needs to be added to Documentation, especially information about relative paths, because it's making yours notes library very portable, every link wont be broken doesn't matter where you're going to place it on your PC or on a server, like GitHub.

**Comment by nathanlesage** [comment]
> I think such miscelannious stuff needs to be added to Documentation, especially information about relative paths, because it's making yours notes library very portable, every link wont be broken doesn't matter where you're going to place it on your PC or on a server, like GitHub.

@MatveyM11 Feel free to suggest documentation updates over in the repo: https://github.com/Zettlr/zettlr-docs

I can't fully keep it updated both because many things don't need to be documented for me (as I know the code in and out) and because it takes a ton of my time, which I'd rather spend on fixing bugs and improving the app.
